name: Check for a new markdown file in docs/people
on:
  pull_request:
    paths:
      - 'docs/people/*.md'

jobs:
  check-for-new-md:
    runs-on: ubuntu-latest
    env:
      Approve: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if only one file was added in the pr
        if: github.event.pull_request.additions != 1
        run: |
          echo "Error! Expected exactly 1 file to be added." >> $GITHUB_OUTPUT
          echo "Approve=false" >> $GITHUB_ENV
          exit 1
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MERGE_LABELS: ""
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

